# Project information
name: boilerplate
description: A new Flutter project for high-level application templates.

# Publishing configuration
publish_to: "none"

# Versioning
version: 1.0.1+2

# Environment setup
environment:
  sdk: ">=3.2.6"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 8.1.3
  bloc_concurrency: 0.2.3
  get_it: 7.6.7
  freezed_annotation: 2.4.1
  dio: 5.4.0
  intl_utils: 2.8.7
  rxdart: 0.27.7
  flutter_svg: 2.0.9
  go_router: 13.1.0
  cupertino_icons: 1.0.6
  another_flushbar: 1.12.30
  shared_preferences: 2.2.2
  talker_dio_logger: 4.0.0
  rest_client:
    path: packages/rest_client
  local_database:
    path: packages/local_database
  talker_bloc_logger: 4.0.0
  talker_flutter: 4.0.0
  flutter_native_splash: 2.3.10

# Dependency overrides
dependency_overrides:
  intl: 0.19.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 3.0.1
  freezed: 2.4.6
  build_runner:
  bloc_test: 9.1.5
  mockito: 5.4.4
  flutter_gen_runner:
  melos: 3.4.0

# Code generation
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

# Flutter configuration
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

# Internationalization
flutter_intl:
  enabled: true
