name: rest_client
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: '>=3.2.6'

dependencies:
  flutter:
    sdk: flutter

  dio: 5.4.0
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  retrofit: 4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1
  freezed: 2.4.6
  json_serializable: 6.7.1
  retrofit_generator: 8.0.6
  build_runner: 2.4.8

flutter:
